import type { IconType } from "react-icons";
import {
  FiActivity,
  FiAward,
  FiBookOpen,
  FiBriefcase,
  FiCode,
  FiCpu,
  FiFolder,
  FiGithub,
  FiGrid,
  FiHeart,
  FiImage,
  FiInstagram,
  FiLayers,
  FiLayout,
  FiLinkedin,
  FiMail,
  FiMapPin,
  FiMessageSquare,
  FiMic,
  FiMonitor,
  FiMusic,
  FiPhone,
  FiServer,
  FiStar,
  FiTrendingUp,
  FiUser,
  FiZap,
} from "react-icons/fi";

const iconMap: Record<string, IconType> = {
  activity: FiActivity,
  award: FiAward,
  "book-open": FiBookOpen,
  briefcase: FiBriefcase,
  code: FiCode,
  cpu: FiCpu,
  folder: FiFolder,
  github: FiGithub,
  grid: FiGrid,
  heart: FiHeart,
  image: FiImage,
  instagram: FiInstagram,
  layers: FiLayers,
  layout: FiLayout,
  linkedin: FiLinkedin,
  mail: FiMail,
  "map-pin": FiMapPin,
  message: FiMessageSquare,
  mic: FiMic,
  monitor: FiMonitor,
  music: FiMusic,
  phone: FiPhone,
  server: FiServer,
  star: FiStar,
  "trending-up": FiTrendingUp,
  user: FiUser,
  zap: FiZap,
};

export const getIconComponent = (iconName?: string, fallback: IconType = FiStar) => {
  if (!iconName) return fallback;
  return iconMap[iconName.toLowerCase()] || fallback;
};
